import fotoForum1 from '../../../images/forumFoto1.png';
import fotoForum2 from '../../../images/forumFoto2.png';
import fotoForum3 from '../../../images/forumFoto3.png';

//данные для массива arrClothes новинки
import newDress1 from "../../../images/newdress1.jpg";
import newDress2 from "../../../images/newdress2.jpg";
import newDress3 from "../../../images/newdress3.jpg";
import newDress4 from "../../../images/newdress4.jpg";

//данные для массива arrClothes
import dress from "../../../images/pattern-dress.png";
import coat from "../../../images/pattern-coat.png";
import palto2 from "../../../images/palto2.jpg";
import kurtka1 from "../../../images/kurtka1.jpg";
import kurtka12 from "../../../images/kurtka12.jpg";
import kurtka13 from "../../../images/kurtka13.jpg";
import blouse from "../../../images/pattern-blouse.png";
import techpic from "../../../images/techpic.jpg";

//данные для комментарий
import commentsSmile from "../../../images/comments-smile.png";

//данные для каталога
import katalogImage1 from "../../../images/katalogImage1.png";

//данные для KatalogPatterns массива arrKatalogs
import Photo1 from "../../../images/Photo.png";
import Photo2 from "../../../images/Photo (1).png";
import Photo3 from "../../../images/Photo (2).png";
import Photo4 from "../../../images/Photo (3).png";

//массив с объектами, в которых имеются изображения пользователей(их сшитые изделия по выкройке)(от пользователей)
export const arrForum = [
  {
    id: 1,
    image: [fotoForum1, fotoForum2, fotoForum3]
  },
  {
    id: 2,
    image: [fotoForum2, fotoForum3, fotoForum1]
  },
  {
    id: 3,
    image: [fotoForum2, fotoForum3],
  },
  {
    id: 4,
    image: [fotoForum1, fotoForum2],
  },
  {
    id: 5,
    image: [fotoForum3, fotoForum3],
  },
];

export const arrPatterns = [
  {
    id: 1,
    image: dress,
    name: "Платье Очарованье",
    text: "женское платье",
    price: 135.00,
    hoveredImage: techpic,
  },
  {
    id: 2,
    image: coat,
    name: "Пальто осень-весна 2023",
    text: "женское осенне-весеннее пальто",
    price: 135.00,
    hoveredImage: techpic,
  },
  {
    id: 3,
    image: dress,
    name: "Платье Романтика",
    text: "женское платье",
    price: 135.00,
    hoveredImage: techpic,
  },
  {
    id: 4,
    image: blouse,
    name: "Блузка",
    text: "женская повседневная блузка",
    price: 135.00,
    hoveredImage: techpic,
  },
  {
    id: 5,
    image: blouse,
    name: "Блузка",
    text: "женская повседневная блузка",
    price: 135.00,
    hoveredImage: techpic,
  },
  {
    id: 6,
    image: Photo1,
    name: "Белое платье",
    text: "женское платье",
    price: 135.0,
    hoveredImage: techpic,
  },
  {
    id: 7,
    image: Photo2,
    name: "Желтое платье",
    text: "женское платье",
    price: 135.0,
    hoveredImage: techpic,
  },
  {
    id: 8,
    image: Photo3,
    name: "Платье-сарафан",
    text: "платье",
    price: 135.0,
    hoveredImage: techpic,
  },
  {
    id: 9,
    image: Photo4,
    name: "Комплект",
    text: "женское платье",
    price: 135.0,
    hoveredImage: techpic,
  },
  {
    id: 10,
    image: Photo4,
    name: "Комплект",
    text: "женское платье",
    price: 135.0,
    hoveredImage: techpic,
  },
  {
    id: 11,
    image: Photo3,
    name: "Синее платье-сарафан",
    text: "женское платье",
    price: 135.0,
    hoveredImage: techpic,
  },
];

export const arrClothes = [
  {
    id: 0,
    key: "Outerwear",
    titles: "Верхняя одежда",//Верхняя одежда/Пальтишки
    image: coat,
    detailed: "Decor",
    values: [{
      id: 0,
      image: coat,
      number: 11111111, //Выкройка №
      imageModel: [coat, coat, coat],
      title: "Пальто осень-весна 2023",
      text: "женское осенне-весеннее пальто",
      price: 135.00,  //цена
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh", //описание
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s", //расход материала
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh", //рекомендации по материалам
    },
    {
      id: 1,
      image: palto2,
      number: 11111112,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s",
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
    },
    {
      id: 2,
      image: kurtka1,
      number: 11111113,
      imageModel: [kurtka1, kurtka12, kurtka13],
      title: "Пальто осень-весна 2023",
      text: "женское осенне-весеннее пальто",
      price: 135.00,
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s",
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
    },
    {
      id: 3,
      image: palto2,
      number: 11111114,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s",
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
    },
    {
      id: 4,
      image: kurtka1,
      number: 11111115,
      imageModel: [kurtka1, kurtka1, kurtka1],
      title: "Пальто осень-весна 2023",
      text: "женское осенне-весеннее пальто",
      price: 135.00,
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s",
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
    },
    {
      id: 5,
      image: palto2,
      number: 11111116,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s",
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh",
    },
    {
      id: 5,
      image: kurtka1,
      imageModel: [kurtka1, kurtka1, kurtka1],
      title: "Пальто осень-весна 2023",
      text: "женское осенне-весеннее пальто",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 7,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    },
    {
      id: 8,
      image: coat,
      imageModel: [coat, coat, coat],
      title: "Пальто осень-весна 2023",
      text: "женское осенне-весеннее пальто",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 9,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    },
    {
      id: 10,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    },
    {
      id: 11,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    },
    {
      id: 12,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    },
    {
      id: 13,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    },
    {
      id: 14,
      image: palto2,
      imageModel: [palto2, palto2, palto2],
      title: "Пусть будет пальто",
      text: "женское пальто",
      price: 131.00,
      hoveredImage: techpic,
    }]
  },
  {
    id: 1,
    key: "Dresses",
    titles: "Платья/Dresses",//Платья
    image: dress,
    detailed: "Decor",
    values: [{
      id: 0,
      image: dress,
      imageModel: [dress, dress, dress],
      title: "Платье Романтика",
      text: "женское платье",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 1,
      active: "new",
      image: newDress1,
      name: "Modern Kitchen",
      text: "женское платье",
      price: 135.0,
    },
    {
      id: 2,
      active: "new",
      image: newDress2,
      name: "Modern Kitchen",
      text: "женское платье",
      price: 135.0,
    },
    {
      id: 3,
      active: "new",
      image: newDress3,
      name: "Modern Kitchen",
      text: "женское платье",
      price: 135.0,
    },
    {
      id: 4,
      active: "new",
      image: newDress4,
      name: "Modern Kitchen",
      text: "женское платье",
      price: 135.0,
    },
    {
      id: 5,
      active: "new",
      image: newDress1,
      name: "Modern Kitchen",
      text: "женское платье",
      price: 135.0,
    },
    {
      id: 6,
      active: "new",
      image: newDress2,
      name: "Modern Kitchen",
      text: "женское платье",
      price: 135.0,
    },
    {
      id: 7,
      image: Photo1,
      imageModel: [Photo1, Photo1, Photo1],
      title: "Белое платье",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 8,
      image: Photo2,
      imageModel: [Photo2, Photo2, Photo2],
      title: "Желтое платье",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 9,
      image: Photo3,
      imageModel: [Photo3, Photo3, Photo3],
      title: "Платье-сарафан",
      text: "платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 10,
      image: Photo4,
      imageModel: [Photo4, Photo4, Photo4],
      title: "Комплект",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 11,
      image: Photo3,
      imageModel: [Photo3, Photo3, Photo3],
      title: "Синее платье-сарафан",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 12,
      image: dress,
      imageModel: [dress, dress, dress],
      title: "Платье Романтика",
      text: "женское платье",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 13,
      image: Photo1,
      imageModel: [Photo1, Photo1, Photo1],
      title: "Белое платье",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 14,
      image: Photo2,
      imageModel: [Photo2, Photo2, Photo2],
      title: "Желтое платье",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 15,
      image: Photo3,
      imageModel: [Photo3, Photo3, Photo3],
      title: "Платье-сарафан",
      text: "платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 16,
      image: Photo4,
      imageModel: [Photo4, Photo4, Photo4],
      title: "Комплект",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    },
    {
      id: 17,
      image: katalogImage1,
      imageModel: [katalogImage1, katalogImage1, katalogImage1],
      title: "Синее платье-сарафан",
      text: "женское платье",
      price: 135.0,
      hoveredImage: techpic,
    }]
  },
  {
    id: 2,
    key: "Вlouses",
    titles: "Блузки/Вlouses",//Блузки
    image: blouse,
    detailed: "Decor",
    values: [{
      id: 0,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
      description: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh", //описание
      materialСonsumption: "dfkjkl  flkjl sjkl sf jl;s df;lj x kl; s l;k s", //расход материала
      recommendations: "dsfskdgfkf sgfkhsd gfkd gskdkfk jkshkdfjhjksdhfh", //рекомендации по материалам
    },
    {
      id: 1,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 2,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 3,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 4,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 5,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 6,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 7,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Блузка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    }]
  },
  {
    id: 3,
    key: "Skirts",
    titles: "Юбки/Skirts",//Юбки
    image: blouse,
    detailed: "Decor",
    values: [{
      id: 1,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 2,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 3,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 4,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 5,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 6,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 7,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 8,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Юбка",
      text: "женская повседневная блузка",
      price: 135.00,
      hoveredImage: techpic,
    }]
  },
  {
    id: 4,
    key: "Jackets",
    titles: "Жакеты/Jackets",//Жакеты
    image: blouse,
    detailed: "Decor",
    values: [{
      id: 1,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакеты",
      text: "женский жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 2,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакеты",
      text: "женский жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 3,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакеты",
      text: "женский жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 4,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакеты",
      text: "женский жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 5,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакеты",
      text: "Жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 6,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакет",
      text: "Жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 7,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакет",
      text: "женский жакет",
      price: 135.00,
      hoveredImage: techpic,
    },
    {
      id: 8,
      image: blouse,
      imageModel: [blouse, blouse, blouse],
      title: "Жакет",
      text: "Жакет",
      price: 135.00,
      hoveredImage: techpic,
    }]
  }]

export const arrComments = [
  {
    id: 1,
    avatar: commentsSmile,
    name: "Романова Инна",
    text: "Все нравиться! Все супер! Носится!",
    marka: "жакет для школы",
  },
  {
    id: 2,
    avatar: commentsSmile,
    name: "Алексеева Елена",
    text: "Все нравиться! Все супер! Носится!",
    marka: "жакет для школы",
  },
  {
    id: 3,
    avatar: commentsSmile,
    name: "Малыгина Татьяна",
    text: "Все нравиться! Все супер! Носится!",
    marka: "жакет для школы",
  },
  {
    id: 4,
    avatar: commentsSmile,
    name: "Иванова Елена",
    text: "Все нравиться! Все супер! Носится!",
    marka: "жакет для школы",
  },
  {
    id: 5,
    avatar: commentsSmile,
    name: "Алексеев Олег",
    text: "Все нравиться! Все супер! Носится!",
    marka: "жакет для школы",
  },
  {
    id: 6,
    avatar: commentsSmile,
    name: "Алексеев Олег",
    text: "Все нравиться! Все супер! Носится!",
    marka: "жакет для школы",
  },
];